import type { Listing } from "./types";

// ~12 realistic Dutch sample listings around Utrecht (matching the mockup
// inventory). This same array feeds scripts/seed.ts once Supabase is
// connected; the SVG placeholder photos get replaced by real photos in
// Supabase Storage at that point.
export const SAMPLE_LISTINGS: Listing[] = [
  {
    id: "bosch-accuboormachine",
    title: "Bosch accuboormachine 18V",
    description:
      "Krachtige accuboormachine van Bosch (GSR 18V) met twee accu's, lader en bitset. Ideaal voor klussen in huis.",
    pricePerDay: 4,
    category: "others",
    condition: "Goed",
    city: "Utrecht Oost",
    postcode: "3581 CD",
    photos: ["/listings/bosch-accuboormachine.svg"],
    rating: 4.8,
    ratingCount: 23,
    ownerName: "Jeroen",
  },
  {
    id: "karcher-hogedrukreiniger",
    title: "Kärcher K5 hogedrukreiniger",
    description:
      "Kärcher K5 Premium hogedrukreiniger met terrasreiniger-opzetstuk. Perfect voor terras, tegels en de auto.",
    pricePerDay: 9,
    category: "garden-tools",
    condition: "Zo goed als nieuw",
    city: "Vleuten",
    postcode: "3451 WD",
    photos: ["/listings/karcher-hogedrukreiniger.svg"],
    rating: 4.6,
    ratingCount: 17,
    ownerName: "Sanne",
  },
  {
    id: "partytent",
    title: "Partytent 3×6 meter",
    description:
      "Ruime witte partytent met afneembare zijwanden. Opzetten kan met twee personen in een half uur. Incl. haringen en touw.",
    pricePerDay: 15,
    category: "others",
    condition: "Goed",
    city: "De Meern",
    postcode: "3453 KL",
    photos: ["/listings/partytent.svg"],
    rating: 4.4,
    ratingCount: 9,
    ownerName: null,
  },
  {
    id: "ps4-controller",
    title: "PS4 controller (DualShock 4)",
    description:
      "Originele Sony DualShock 4 controller, zwart. Handig als je vrienden over de vloer hebt voor een game-avond.",
    pricePerDay: 2,
    category: "gaming",
    condition: "Goed",
    city: "Utrecht",
    postcode: "3521 AB",
    photos: ["/listings/ps4-controller.svg"],
    rating: 4.9,
    ratingCount: 31,
    ownerName: "Mike",
  },
  {
    id: "ladder",
    title: "Ladder 3-delig aluminium",
    description:
      "Stevige 3-delige aluminium reformladder van Altrex, werkhoogte tot 7 meter. Voor schilderen of dakgoot schoonmaken.",
    pricePerDay: 6,
    category: "others",
    condition: "Gebruikt",
    city: "Leidsche Rijn",
    postcode: "3541 EH",
    photos: ["/listings/ladder.svg"],
    rating: 4.5,
    ratingCount: 12,
    ownerName: "Fatima",
  },
  {
    id: "elektrische-gitaar",
    title: "Elektrische gitaar | Model 465",
    description:
      "Elektrische gitaar (Yamaha Pacifica) inclusief kleine oefenversterker en kabel. Leuk om uit te proberen voor je er zelf één koopt.",
    pricePerDay: 10,
    category: "music-instruments",
    condition: "Goed",
    city: "Utrecht",
    postcode: "3511 LX",
    photos: ["/listings/elektrische-gitaar.svg"],
    rating: 5,
    ratingCount: 8,
    ownerName: "Daan",
  },
  {
    id: "grasmaaier",
    title: "Grasmaaier Bosch Rotak 34",
    description:
      "Elektrische grasmaaier van Bosch met 40 liter opvangbak en 30 meter verlengsnoer. Voor kleine en middelgrote tuinen.",
    pricePerDay: 7,
    category: "garden-tools",
    condition: "Goed",
    city: "Vleuten",
    postcode: "3451 GB",
    photos: ["/listings/grasmaaier.svg"],
    rating: 4.3,
    ratingCount: 14,
    ownerName: "Peter",
  },
  {
    id: "heggenschaar",
    title: "Elektrische heggenschaar",
    description:
      "Elektrische heggenschaar van Gardena, 50 cm meslengte. Licht en handig, snoer van 20 meter inbegrepen.",
    pricePerDay: 5,
    category: "garden-tools",
    condition: "Goed",
    city: "Utrecht",
    postcode: "3527 CV",
    photos: ["/listings/heggenschaar.svg"],
    rating: 4.7,
    ratingCount: 11,
    ownerName: null,
  },
  {
    id: "nintendo-switch",
    title: "Nintendo Switch + Mario Kart",
    description:
      "Nintendo Switch console met twee Joy-Cons, dock en Mario Kart 8 Deluxe. Perfect voor een spelletjesavond of weekendje weg.",
    pricePerDay: 8,
    category: "gaming",
    condition: "Zo goed als nieuw",
    city: "Utrecht",
    postcode: "3582 GT",
    photos: ["/listings/nintendo-switch.svg"],
    rating: 4.9,
    ratingCount: 26,
    ownerName: "Lisa",
  },
  {
    id: "saxofoon",
    title: "Saxofoon | Model 90",
    description:
      "Altsaxofoon (Yamaha YAS-280) met koffer, riem en drie rieten. Goed onderhouden, mooi warm geluid.",
    pricePerDay: 12,
    category: "music-instruments",
    condition: "Goed",
    city: "Vleuten",
    postcode: "3451 RC",
    photos: ["/listings/saxofoon.svg"],
    rating: 4.8,
    ratingCount: 6,
    ownerName: "Willem",
  },
  {
    id: "zitzak",
    title: "Zitzak XXL (Fatboy)",
    description:
      "Originele Fatboy zitzak in oranje. Extra zitplekken voor een feestje, filmavond of logees.",
    pricePerDay: 3,
    category: "furniture",
    condition: "Goed",
    city: "Utrecht",
    postcode: "3512 JE",
    photos: ["/listings/zitzak.svg"],
    rating: 4.2,
    ratingCount: 7,
    ownerName: "Anouk",
  },
  {
    id: "klaptafel-stoelen",
    title: "Klaptafel + 4 klapstoelen",
    description:
      "Inklapbare tafel (180 cm) met vier klapstoelen. Zo mee te nemen in de auto — handig voor verjaardagen en buurtborrels.",
    pricePerDay: 6,
    category: "furniture",
    condition: "Gebruikt",
    city: "De Meern",
    postcode: "3453 ME",
    photos: ["/listings/klaptafel-stoelen.svg"],
    rating: 4.6,
    ratingCount: 10,
    ownerName: "Bram",
  },
  {
    id: "vouwfiets",
    title: "Vouwfiets (Brompton)",
    description:
      "Brompton vouwfiets, 3 versnellingen. Handig voor bezoek dat met de trein komt of een dagje er op uit.",
    pricePerDay: 10,
    category: "others",
    condition: "Goed",
    city: "Utrecht",
    postcode: "3511 AD",
    photos: ["/listings/vouwfiets.svg"],
    rating: 4.7,
    ratingCount: 19,
    ownerName: "Ingrid",
  },
];
