import type { Listing } from "./types";

// ~13 realistic Dutch sample listings around Utrecht (matching the mockup
// inventory). Artwork = emoji on gradient, exactly like the prototype;
// real photos replace it via the `photos` array once Supabase Storage is
// seeded. This same array feeds scripts/seed.ts at that point.
export const SAMPLE_LISTINGS: Listing[] = [
  {
    id: "bosch-accuboormachine",
    title: "Bosch accuboormachine 18V",
    description:
      "Krachtige accuboormachine van Bosch (GSR 18V) met twee accu's, lader en bitset. Ideaal voor klussen in huis.",
    pricePerDay: 4,
    category: "others",
    condition: "Goed",
    city: "Utrecht Oost",
    postcode: "3581 CD",
    photos: [],
    emoji: "🛠️",
    bg: "linear-gradient(135deg,#0e5c4a,#2e8b6f)",
    rating: 4.8,
    ratingCount: 23,
    availableFrom: "25/07/2026",
    availableTo: "28/07/2026",
    ownerName: "Jeroen",
  },
  {
    id: "karcher-hogedrukreiniger",
    title: "Kärcher K5 hogedrukreiniger",
    description:
      "Kärcher K5 Premium hogedrukreiniger met terrasreiniger-opzetstuk. Perfect voor terras, tegels en de auto.",
    pricePerDay: 9,
    category: "garden-tools",
    condition: "Zo goed als nieuw",
    city: "Vleuten",
    postcode: "3451 WD",
    photos: [],
    emoji: "🚿",
    bg: "linear-gradient(135deg,#2c3e50,#4b6584)",
    rating: 4.6,
    ratingCount: 17,
    availableFrom: "20/07/2026",
    availableTo: "03/08/2026",
    ownerName: "Sanne",
  },
  {
    id: "partytent",
    title: "Partytent 3×6 meter",
    description:
      "Ruime witte partytent met afneembare zijwanden. Opzetten kan met twee personen in een half uur. Incl. haringen en touw.",
    pricePerDay: 15,
    category: "others",
    condition: "Goed",
    city: "De Meern",
    postcode: "3453 KL",
    photos: [],
    emoji: "⛺",
    bg: "linear-gradient(135deg,#00695c,#4db6ac)",
    rating: 4.4,
    ratingCount: 9,
    availableFrom: "01/08/2026",
    availableTo: "31/08/2026",
    ownerName: null,
  },
  {
    id: "ps4-controller",
    title: "PS4 controller (DualShock 4)",
    description:
      "Originele Sony DualShock 4 controller, zwart. Handig als je vrienden over de vloer hebt voor een game-avond.",
    pricePerDay: 2,
    category: "gaming",
    condition: "Goed",
    city: "Utrecht",
    postcode: "3521 AB",
    photos: [],
    emoji: "🎮",
    bg: "linear-gradient(135deg,#f7b733,#fc4a1a)",
    rating: 4.9,
    ratingCount: 31,
    availableFrom: "18/07/2026",
    availableTo: "01/09/2026",
    ownerName: "Mike",
  },
  {
    id: "ladder",
    title: "Ladder 3-delig aluminium",
    description:
      "Stevige 3-delige aluminium reformladder van Altrex, werkhoogte tot 7 meter. Voor schilderen of dakgoot schoonmaken.",
    pricePerDay: 6,
    category: "others",
    condition: "Gebruikt",
    city: "Leidsche Rijn",
    postcode: "3541 EH",
    photos: [],
    emoji: "🪜",
    bg: "linear-gradient(135deg,#8d99ae,#bfc9d4)",
    rating: 4.5,
    ratingCount: 12,
    availableFrom: "22/07/2026",
    availableTo: "29/07/2026",
    ownerName: "Fatima",
  },
  {
    id: "elektrische-gitaar",
    title: "Elektrische gitaar | Model 465",
    description:
      "Elektrische gitaar (Yamaha Pacifica) inclusief kleine oefenversterker en kabel. Leuk om uit te proberen voor je er zelf één koopt.",
    pricePerDay: 10,
    category: "music-instruments",
    condition: "Goed",
    city: "Utrecht",
    postcode: "3511 LX",
    photos: [],
    emoji: "🎸",
    bg: "linear-gradient(135deg,#6a5acd,#b0a6e8)",
    rating: 5,
    ratingCount: 8,
    availableFrom: "25/07/2026",
    availableTo: "28/07/2026",
    ownerName: "Daan",
  },
  {
    id: "grasmaaier",
    title: "Grasmaaier Bosch Rotak 34",
    description:
      "Elektrische grasmaaier van Bosch met 40 liter opvangbak en 30 meter verlengsnoer. Voor kleine en middelgrote tuinen.",
    pricePerDay: 7,
    category: "garden-tools",
    condition: "Goed",
    city: "Vleuten",
    postcode: "3451 GB",
    photos: [],
    emoji: "🌱",
    bg: "linear-gradient(135deg,#33691e,#8bc34a)",
    rating: 4.3,
    ratingCount: 14,
    availableFrom: "19/07/2026",
    availableTo: "26/07/2026",
    ownerName: "Peter",
  },
  {
    id: "heggenschaar",
    title: "Elektrische heggenschaar",
    description:
      "Elektrische heggenschaar van Gardena, 50 cm meslengte. Licht en handig, snoer van 20 meter inbegrepen.",
    pricePerDay: 5,
    category: "garden-tools",
    condition: "Goed",
    city: "Utrecht",
    postcode: "3527 CV",
    photos: [],
    emoji: "✂️",
    bg: "linear-gradient(135deg,#2e7d32,#81c784)",
    rating: 4.7,
    ratingCount: 11,
    availableFrom: "01/08/2026",
    availableTo: "09/08/2026",
    ownerName: null,
  },
  {
    id: "nintendo-switch",
    title: "Nintendo Switch + Mario Kart",
    description:
      "Nintendo Switch console met twee Joy-Cons, dock en Mario Kart 8 Deluxe. Perfect voor een spelletjesavond of weekendje weg.",
    pricePerDay: 8,
    category: "gaming",
    condition: "Zo goed als nieuw",
    city: "Utrecht",
    postcode: "3582 GT",
    photos: [],
    emoji: "🕹️",
    bg: "linear-gradient(135deg,#c62828,#ef5350)",
    rating: 4.9,
    ratingCount: 26,
    availableFrom: "24/07/2026",
    availableTo: "27/07/2026",
    ownerName: "Lisa",
  },
  {
    id: "saxofoon",
    title: "Saxofoon | Model 90",
    description:
      "Altsaxofoon (Yamaha YAS-280) met koffer, riem en drie rieten. Goed onderhouden, mooi warm geluid.",
    pricePerDay: 12,
    category: "music-instruments",
    condition: "Goed",
    city: "Vleuten",
    postcode: "3451 RC",
    photos: [],
    emoji: "🎷",
    bg: "linear-gradient(135deg,#caa04b,#f0d495)",
    rating: 4.8,
    ratingCount: 6,
    availableFrom: "26/07/2026",
    availableTo: "02/08/2026",
    ownerName: "Willem",
  },
  {
    id: "zitzak",
    title: "Zitzak XXL (Fatboy)",
    description:
      "Originele Fatboy zitzak in oranje. Extra zitplekken voor een feestje, filmavond of logees.",
    pricePerDay: 3,
    category: "furniture",
    condition: "Goed",
    city: "Utrecht",
    postcode: "3512 JE",
    photos: [],
    emoji: "🛋️",
    bg: "linear-gradient(135deg,#c0392b,#e57368)",
    rating: 4.2,
    ratingCount: 7,
    availableFrom: "21/07/2026",
    availableTo: "04/08/2026",
    ownerName: "Anouk",
  },
  {
    id: "klaptafel-stoelen",
    title: "Klaptafel + 4 klapstoelen",
    description:
      "Inklapbare tafel (180 cm) met vier klapstoelen. Zo mee te nemen in de auto — handig voor verjaardagen en buurtborrels.",
    pricePerDay: 6,
    category: "furniture",
    condition: "Gebruikt",
    city: "De Meern",
    postcode: "3453 ME",
    photos: [],
    emoji: "🪑",
    bg: "linear-gradient(135deg,#5d4037,#a1887f)",
    rating: 4.6,
    ratingCount: 10,
    availableFrom: "25/07/2026",
    availableTo: "28/07/2026",
    ownerName: "Bram",
  },
  {
    id: "vouwfiets",
    title: "Vouwfiets (Brompton)",
    description:
      "Brompton vouwfiets, 3 versnellingen. Handig voor bezoek dat met de trein komt of een dagje er op uit.",
    pricePerDay: 10,
    category: "others",
    condition: "Goed",
    city: "Utrecht",
    postcode: "3511 AD",
    photos: [],
    emoji: "🚲",
    bg: "linear-gradient(135deg,#1565c0,#64b5f6)",
    rating: 4.7,
    ratingCount: 19,
    availableFrom: "20/07/2026",
    availableTo: "10/08/2026",
    ownerName: "Ingrid",
  },
];
